# -*- coding: utf-8 -*-
"""Healthcare-Agentic-AI- System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itPWq8Jfsb83t7nJQ6HPtGUas1fJs94J

# South African Healthcare AI System

## Objective
Multi-agent AI system to assist triage, medical guidance, and follow-up care using Groq + LangGraph + FAISS.

## Architecture

Patient Query
      |
      v
Supervisor Agent (LangGraph Router)
      |
      +--> Triage Agent
      +--> Medical RAG Agent (FAISS)
      +--> Follow-Up Agent
      +--> Translation Agent
      |
      v
Final Response

## Tech Stack
- Groq (Llama 3.3 70B)
- LangGraph
- FAISS Vector Database
- Sentence Transformers
- Python (Colab)

“This system is designed as an agentic workflow, not a chatbot, enabling dynamic routing and modular clinical decision support.”
"""

!pip install -q \
langgraph \
langchain \
langchain-core \
langchain-community \
langchain-groq \
faiss-cpu \
pypdf \
sentence-transformers \
python-dotenv

import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("GROQ_NEW_KEY")

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

response = llm.invoke(
    "What are common symptoms of tuberculosis?"
)

print(response.content)

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage
import os

class HealthcareState(TypedDict):
    patient_query: str
    triage_result: str
    medical_response: str
    followup_plan: str

def triage_agent(state: HealthcareState):

    query = state["patient_query"]

    prompt = f"""
    You are a healthcare triage assistant.

    Classify the patient into:

    - EMERGENCY
    - URGENT
    - ROUTINE

    Symptoms:

    {query}

    Return:
    Risk Level
    Explanation
    """

    response = llm.invoke(prompt)

    return {
        "triage_result": response.content
    }

def medical_agent(state: HealthcareState):

    query = state["patient_query"]

    prompt = f"""
    You are a medical assistant for South Africa.

    Patient query:

    {query}

    Provide:

    - Possible causes
    - Recommended actions
    - Warning signs

    Do NOT diagnose.
    """

    response = llm.invoke(prompt)

    return {
        "medical_response": response.content
    }

def followup_agent(state: HealthcareState):

    prompt = f"""
    Based on this triage result:

    {state['triage_result']}

    Create:

    - Follow-up instructions
    - Medication reminder suggestions
    - Next appointment recommendation
    """

    response = llm.invoke(prompt)

    return {
        "followup_plan": response.content
    }

def route_patient(state):

    triage = state["triage_result"].upper()

    if "EMERGENCY" in triage:
        return "emergency"

    return "normal"

def emergency_agent(state: HealthcareState):

    return {
        "medical_response":
        """
        EMERGENCY DETECTED

        Seek immediate medical attention.
        Call emergency services.
        Visit nearest hospital immediately.
        """
    }

workflow = StateGraph(HealthcareState)

workflow.add_node("triage", triage_agent)
workflow.add_node("medical", medical_agent)
workflow.add_node("followup", followup_agent)
workflow.add_node("emergency", emergency_agent)

workflow.set_entry_point("triage")

workflow.add_conditional_edges(
    "triage",
    route_patient,
    {
        "emergency": "emergency",
        "normal": "medical"
    }
)

workflow.add_edge("medical", "followup")

workflow.add_edge("followup", END)
workflow.add_edge("emergency", END)

app = workflow.compile()

result = app.invoke(
    {
        "patient_query":
        "I have chest pain, difficulty breathing and severe dizziness."
    }
)

print(result)

class HealthcareState(TypedDict):
    patient_id: str
    messages: list  # conversation history
    patient_query: str

def memory_agent(state):
    history = state.get("messages", [])

    history.append({
        "role": "user",
        "content": state["patient_query"]
    })

    return {"messages": history}

def calculator_tool(expression: str):
    try:
        return str(eval(expression))
    except:
        return "Invalid expression"

def symptom_checker(symptoms: str):

    symptoms = symptoms.lower()

    if "chest pain" in symptoms and "breathing" in symptoms:
        return "HIGH RISK: possible cardiac or respiratory emergency"

    if "fever" in symptoms and "cough" in symptoms:
        return "Possible infection (TB / flu / pneumonia)"

    return "Low risk but monitor symptoms"

def tool_router(state):

    query = state["patient_query"]

    if "calculate" in query:
        return "calculator"

    if "symptom" in query:
        return "symptom_checker"

    return "medical"

def structured_medical_output(state):

    prompt = f"""
    Convert this into a medical report JSON:

    {state['medical_response']}

    Return ONLY JSON with:

    {{
      "risk_level": "",
      "possible_conditions": [],
      "recommended_actions": [],
      "follow_up_days": number,
      "emergency": true/false
    }}
    """

    response = llm.invoke(prompt)

    return {"final_response": response.content}

def hallucination_checker(state):

    prompt = f"""
    You are a medical safety validator.

    Check if this response is medically unsafe or hallucinated:

    RESPONSE:
    {state['medical_response']}

    Rules:
    - No fake drugs
    - No false diagnosis
    - Must align with general medical guidelines

    Return:
    SAFE or UNSAFE + reason
    """

    result = llm.invoke(prompt)

    return {"evaluation": result.content}

def safety_router(state):

    if "UNSAFE" in state.get("evaluation", ""):
        return "retriage"

    return "final"

!pip install faiss-cpu pypdf langchain sentence-transformers

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/2019-art-guideline.pdf")
docs = loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150
)

chunks = splitter.split_documents(docs)

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

db = FAISS.from_documents(chunks, embeddings)

retriever = db.as_retriever(search_kwargs={"k": 4})

docs = retriever.invoke("TB symptoms treatment")
context = "\n".join([d.page_content for d in docs])

def supervisor(state):

    query = state["patient_query"].lower()

    tasks = []

    if "zulu" in query or "translate" in query:
        tasks.append("translation")

    if "pain" in query or "breathing" in query:
        tasks.append("triage")

    tasks.append("medical")

    return {"next_agents": tasks}

import sys
sys.path.append("/content")

!PYTHONPATH=/content uvicorn app.main:app --host 0.0.0.0 --port 8000

!pip install pyngrok

from pyngrok import ngrok

# Replace 'YOUR_NGROK_AUTHTOKEN' with your actual ngrok authtoken
ngrok.set_auth_token("3F3sRdrtx46kzVtg8JP3TgRQs0X_3ugdf8cYpPKjvBywBmGWM")

public_url = ngrok.connect(8000)
print(public_url)

from fastapi import FastAPI
from app.routes.chat import router as chat_router
from app.routes.webhook import router as whatsapp_router

app = FastAPI(title="Healthcare AI Agent System")

app.include_router(chat_router)
app.include_router(whatsapp_router)

!mkdir -p app/routes
!mkdir -p app/graph
!touch app/__init__.py
!touch app/routes/__init__.py
!touch app/graph/__init__.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/routes/chat.py
# from fastapi import APIRouter
# from app.graph.langgraph_flow import app as graph_app # This import will be resolved after creating langgraph_flow.py
# 
# router = APIRouter()
# 
# @router.post("/chat")
# def chat(payload: dict):
# 
#     result = graph_app.invoke({
#         "patient_query": payload["message"],
#         "patient_id": payload.get("patient_id", "anon")
#     })
# 
#     return result

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/routes/webhook.py
# from fastapi import APIRouter, Request
# import requests
# 
# router = APIRouter()
# 
# def send_whatsapp(text):
# 
#     url = "https://graph.facebook.com/v18.0/YOUR_PHONE_ID/messages"
# 
#     payload = {
#         "messaging_product": "whatsapp",
#         "to": "USER_NUMBER",
#         "text": {"body": text}
#     }
# 
#     headers = {
#         "Authorization": "Bearer YOUR_TOKEN",
#         "Content-Type": "application/json"
#     }
# 
#     requests.post(url, json=payload, headers=headers)
# 
# @router.post("/webhook")
# async def whatsapp_webhook(request: Request):
# 
#     data = await request.json()
# 
#     message = data["entry"][0]["changes"][0]["value"]["messages"][0]["text"]["body"]
# 
#     # This will be resolved after creating langgraph_flow.py
#     from app.graph.langgraph_flow import app as graph_app
#     result = graph_app.invoke({
#         "patient_query": message,
#         "patient_id": "whatsapp_user"
#     })
# 
#     reply = result["final_response"]
# 
#     send_whatsapp(reply)
# 
#     return {"status": "ok"}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/main.py
# from fastapi import FastAPI
# from app.routes.chat import router as chat_router
# from app.routes.webhook import router as whatsapp_router
# 
# app = FastAPI(title="Healthcare AI Agent System")
# 
# app.include_router(chat_router)
# app.include_router(whatsapp_router)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/graph/langgraph_flow.py
# # This content is from cell PvBHdyQLHYhS, adapted for a file
# from langgraph.graph import StateGraph, END
# from typing import TypedDict, List
# from langchain_groq import ChatGroq
# import os
# 
# # Re-define llm if it's not globally available in this context
# llm = ChatGroq(
#     model="llama-3.3-70b-versatile",
#     temperature=0
# )
# 
# # Define the State TypedDict (from cell 3EVDQJCuG4ki)
# class State(TypedDict):
#     patient_id: str
#     patient_query: str
# 
#     messages: List[str]
# 
#     triage_result: str
#     medical_response: str
# 
#     tool_result: str
# 
#     evaluation: str
#     final_response: str
# 
# # Re-define agent functions (from previous cells) to ensure they are available in this file
# # triage_agent from xPZC6lqc5PLR
# def triage_agent(state: State):
#     query = state["patient_query"]
#     prompt = f"""
#     You are a healthcare triage assistant.
# 
#     Classify the patient into:
# 
#     - EMERGENCY
#     - URGENT
#     - ROUTINE
# 
#     Symptoms:
# 
#     {query}
# 
#     Return:
#     Risk Level
#     Explanation
#     """
#     response = llm.invoke(prompt)
#     return {"triage_result": response.content}
# 
# # medical_agent from MYFksalQ5RMh
# def medical_agent(state: State):
#     query = state["patient_query"]
#     prompt = f"""
#     You are a medical assistant for South Africa.
# 
#     Patient query:
# 
#     {query}
# 
#     Provide:
# 
#     - Possible causes
#     - Recommended actions
#     - Warning signs
# 
#     Do NOT diagnose.
#     """
#     response = llm.invoke(prompt)
#     return {"medical_response": response.content}
# 
# # reflection_agent from TNev9cgwHCrx
# def reflection_agent(state: State):
#     prompt = f"""
#     Evaluate this medical response:
# 
#     {state['medical_response']}
# 
#     Check:
#     - safety
#     - hallucinations
#     - missing warnings
# 
#     Return: SAFE or FIX_REQUIRED
#     """
#     result = llm.invoke(prompt)
#     return {"evaluation": result.content}
# 
# # tool_agent from ez0wAaWhHJRh
# def tool_agent(state: State):
#     query = state["patient_query"]
#     if "calculate" in query:
#         result = eval(query.replace("calculate", ""))
#         return {"tool_result": str(result)}
#     return {"tool_result": "No tool used"}
# 
# # supervisor from o-z3rCkEG8DZ
# def supervisor(state: State):
#     query = state["patient_query"].lower()
#     if "calculate" in query:
#         return "tool"
#     if "pain" in query or "breathing" in query:
#         return "triage"
#     return "medical"
# 
# # safety_router from w9K0SeXgHGUJ
# def safety_router(state: State):
#     if "FIX_REQUIRED" in state["evaluation"]:
#         return "medical"   # loop back
#     return "final"
# 
# 
# graph = StateGraph(State)
# 
# graph.add_node("supervisor", supervisor)
# graph.add_node("triage", triage_agent)
# graph.add_node("medical", medical_agent)
# graph.add_node("tool", tool_agent)
# graph.add_node("reflection", reflection_agent)
# 
# graph.set_entry_point("supervisor")
# 
# graph.add_conditional_edges(
#     "supervisor",
#     supervisor,
#     {
#         "triage": "triage",
#         "medical": "medical",
#         "tool": "tool"
#     }
# )
# 
# graph.add_edge("triage", "medical")
# graph.add_edge("medical", "reflection")
# 
# graph.add_conditional_edges(
#     "reflection",
#     safety_router,
#     {
#         "medical": "medical",
#         "final": END
#     }
# )
# 
# app = graph.compile()



from fastapi import APIRouter
from app.graph.langgraph_flow import app as graph_app

router = APIRouter()

@router.post("/chat")
def chat(payload: dict):

    result = graph_app.invoke({
        "patient_query": payload["message"],
        "patient_id": payload.get("patient_id", "anon")
    })

    return result

from typing import TypedDict, List

class State(TypedDict):
    patient_id: str
    patient_query: str

    messages: List[str]

    triage_result: str
    medical_response: str

    tool_result: str

    evaluation: str
    final_response: str

def supervisor(state):

    query = state["patient_query"].lower()

    if "calculate" in query:
        return "tool"

    if "pain" in query or "breathing" in query:
        return "triage"

    return "medical"

def reflection_agent(state):

    prompt = f"""
    Evaluate this medical response:

    {state['medical_response']}

    Check:
    - safety
    - hallucinations
    - missing warnings

    Return: SAFE or FIX_REQUIRED
    """

    result = llm.invoke(prompt)

    return {"evaluation": result.content}

def safety_router(state):

    if "FIX_REQUIRED" in state["evaluation"]:
        return "medical"   # loop back

    return "final"

def tool_agent(state):

    query = state["patient_query"]

    if "calculate" in query:
        result = eval(query.replace("calculate", ""))

        return {"tool_result": str(result)}

    return {"tool_result": "No tool used"}

from langgraph.graph import StateGraph, END

graph = StateGraph(State)

graph.add_node("supervisor", supervisor)
graph.add_node("triage", triage_agent)
graph.add_node("medical", medical_agent)
graph.add_node("tool", tool_agent)
graph.add_node("reflection", reflection_agent)

graph.set_entry_point("supervisor")

graph.add_conditional_edges(
    "supervisor",
    supervisor,
    {
        "triage": "triage",
        "medical": "medical",
        "tool": "tool"
    }
)

graph.add_edge("triage", "medical")
graph.add_edge("medical", "reflection")

graph.add_conditional_edges(
    "reflection",
    safety_router,
    {
        "medical": "medical",
        "final": END
    }
)

app = graph.compile()

from fastapi import APIRouter, Request
import requests

router = APIRouter()

@router.post("/webhook")
async def whatsapp_webhook(request: Request):

    data = await request.json()

    message = data["entry"][0]["changes"][0]["value"]["messages"][0]["text"]["body"]

    result = graph_app.invoke({
        "patient_query": message,
        "patient_id": "whatsapp_user"
    })

    reply = result["final_response"]

    send_whatsapp(reply)

    return {"status": "ok"}

def send_whatsapp(text):

    url = "https://graph.facebook.com/v18.0/YOUR_PHONE_ID/messages"

    payload = {
        "messaging_product": "whatsapp",
        "to": "USER_NUMBER",
        "text": {"body": text}
    }

    headers = {
        "Authorization": "Bearer YOUR_TOKEN",
        "Content-Type": "application/json"
    }

    requests.post(url, json=payload, headers=headers)

def build_vectorstore(docs):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800,
        chunk_overlap=150
    )

    chunks = splitter.split_documents(docs)

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    db = FAISS.from_documents(chunks, embeddings)

    db.save_local("faiss_sa_medical")

    return db

print(len(docs))
print(docs[0].page_content[:1000])

import os

project_name = "healthcare-agentic-ai-system"
os.makedirs(project_name, exist_ok=True)